/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_POMOFOCUS_BLE_POMOFOCUS_PB_H_INCLUDED
#define PB_POMOFOCUS_BLE_POMOFOCUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _pomofocus_ble_TimerPhase {
    pomofocus_ble_TimerPhase_TIMER_PHASE_IDLE = 0,
    pomofocus_ble_TimerPhase_TIMER_PHASE_FOCUSING = 1,
    pomofocus_ble_TimerPhase_TIMER_PHASE_PAUSED = 2,
    pomofocus_ble_TimerPhase_TIMER_PHASE_SHORT_BREAK = 3,
    pomofocus_ble_TimerPhase_TIMER_PHASE_LONG_BREAK = 4,
    pomofocus_ble_TimerPhase_TIMER_PHASE_BREAK_PAUSED = 5,
    pomofocus_ble_TimerPhase_TIMER_PHASE_REFLECTION = 6,
    pomofocus_ble_TimerPhase_TIMER_PHASE_COMPLETED = 7,
    pomofocus_ble_TimerPhase_TIMER_PHASE_ABANDONED = 8
} pomofocus_ble_TimerPhase;

typedef enum _pomofocus_ble_TimerAction {
    pomofocus_ble_TimerAction_TIMER_ACTION_START = 0,
    pomofocus_ble_TimerAction_TIMER_ACTION_PAUSE = 1,
    pomofocus_ble_TimerAction_TIMER_ACTION_RESUME = 2,
    pomofocus_ble_TimerAction_TIMER_ACTION_ABANDON = 3,
    pomofocus_ble_TimerAction_TIMER_ACTION_SKIP_BREAK = 4,
    pomofocus_ble_TimerAction_TIMER_ACTION_RATE_SESSION = 5
} pomofocus_ble_TimerAction;

typedef enum _pomofocus_ble_GoalType {
    pomofocus_ble_GoalType_GOAL_TYPE_LONG_TERM = 0,
    pomofocus_ble_GoalType_GOAL_TYPE_PROCESS = 1
} pomofocus_ble_GoalType;

typedef enum _pomofocus_ble_SessionType {
    pomofocus_ble_SessionType_SESSION_TYPE_FOCUS = 0,
    pomofocus_ble_SessionType_SESSION_TYPE_SHORT_BREAK = 1,
    pomofocus_ble_SessionType_SESSION_TYPE_LONG_BREAK = 2
} pomofocus_ble_SessionType;

typedef enum _pomofocus_ble_SessionOutcome {
    pomofocus_ble_SessionOutcome_SESSION_OUTCOME_COMPLETED = 0,
    pomofocus_ble_SessionOutcome_SESSION_OUTCOME_ABANDONED = 1
} pomofocus_ble_SessionOutcome;

typedef enum _pomofocus_ble_SyncState {
    pomofocus_ble_SyncState_SYNC_STATE_IDLE = 0,
    pomofocus_ble_SyncState_SYNC_STATE_READY = 1,
    pomofocus_ble_SyncState_SYNC_STATE_TRANSFERRING = 2,
    pomofocus_ble_SyncState_SYNC_STATE_COMPLETE = 3,
    pomofocus_ble_SyncState_SYNC_STATE_ERROR = 4
} pomofocus_ble_SyncState;

typedef enum _pomofocus_ble_SyncCommand {
    pomofocus_ble_SyncCommand_SYNC_COMMAND_START = 0,
    pomofocus_ble_SyncCommand_SYNC_COMMAND_ACK = 1,
    pomofocus_ble_SyncCommand_SYNC_COMMAND_NACK = 2,
    pomofocus_ble_SyncCommand_SYNC_COMMAND_ABORT = 3,
    pomofocus_ble_SyncCommand_SYNC_COMMAND_CURSOR_UPDATE = 4
} pomofocus_ble_SyncCommand;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(16) pomofocus_ble_TimerState_goal_id_t;
typedef struct _pomofocus_ble_TimerState {
    pomofocus_ble_TimerPhase phase;
    uint32_t remaining_seconds;
    uint32_t elapsed_seconds;
    pomofocus_ble_TimerState_goal_id_t goal_id;
    uint32_t session_count;
} pomofocus_ble_TimerState;

typedef PB_BYTES_ARRAY_T(16) pomofocus_ble_TimerCommand_goal_id_t;
typedef struct _pomofocus_ble_TimerCommand {
    pomofocus_ble_TimerAction action;
    pomofocus_ble_TimerCommand_goal_id_t goal_id;
    uint32_t focus_duration;
} pomofocus_ble_TimerCommand;

typedef PB_BYTES_ARRAY_T(16) pomofocus_ble_Goal_id_t;
typedef struct _pomofocus_ble_Goal {
    pomofocus_ble_Goal_id_t id;
    char title[101];
    pomofocus_ble_GoalType type;
    uint32_t target_sessions;
    uint32_t completed_today;
} pomofocus_ble_Goal;

typedef struct _pomofocus_ble_GoalList {
    pb_size_t goals_count;
    pomofocus_ble_Goal goals[10];
} pomofocus_ble_GoalList;

typedef PB_BYTES_ARRAY_T(16) pomofocus_ble_SelectedGoal_goal_id_t;
typedef struct _pomofocus_ble_SelectedGoal {
    pomofocus_ble_SelectedGoal_goal_id_t goal_id;
} pomofocus_ble_SelectedGoal;

typedef PB_BYTES_ARRAY_T(16) pomofocus_ble_SessionRecord_id_t;
typedef PB_BYTES_ARRAY_T(16) pomofocus_ble_SessionRecord_goal_id_t;
typedef struct _pomofocus_ble_SessionRecord {
    pomofocus_ble_SessionRecord_id_t id;
    pomofocus_ble_SessionRecord_goal_id_t goal_id;
    int64_t started_at;
    int64_t ended_at;
    uint32_t planned_duration;
    uint32_t actual_duration;
    pomofocus_ble_SessionType type;
    pomofocus_ble_SessionOutcome outcome;
    uint32_t focus_quality;
    char intention[201];
    char reflection[501];
    char distraction_note[201];
} pomofocus_ble_SessionRecord;

typedef PB_BYTES_ARRAY_T(16) pomofocus_ble_SyncStatus_last_synced_id_t;
typedef struct _pomofocus_ble_SyncStatus {
    uint32_t pending_sessions;
    uint32_t total_stored;
    pomofocus_ble_SyncStatus_last_synced_id_t last_synced_id;
    pomofocus_ble_SyncState state;
} pomofocus_ble_SyncStatus;

typedef PB_BYTES_ARRAY_T(16) pomofocus_ble_SyncControl_last_synced_id_t;
typedef struct _pomofocus_ble_SyncControl {
    pomofocus_ble_SyncCommand command;
    uint32_t ack_count;
    pomofocus_ble_SyncControl_last_synced_id_t last_synced_id;
} pomofocus_ble_SyncControl;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _pomofocus_ble_TimerPhase_MIN pomofocus_ble_TimerPhase_TIMER_PHASE_IDLE
#define _pomofocus_ble_TimerPhase_MAX pomofocus_ble_TimerPhase_TIMER_PHASE_ABANDONED
#define _pomofocus_ble_TimerPhase_ARRAYSIZE ((pomofocus_ble_TimerPhase)(pomofocus_ble_TimerPhase_TIMER_PHASE_ABANDONED+1))

#define _pomofocus_ble_TimerAction_MIN pomofocus_ble_TimerAction_TIMER_ACTION_START
#define _pomofocus_ble_TimerAction_MAX pomofocus_ble_TimerAction_TIMER_ACTION_RATE_SESSION
#define _pomofocus_ble_TimerAction_ARRAYSIZE ((pomofocus_ble_TimerAction)(pomofocus_ble_TimerAction_TIMER_ACTION_RATE_SESSION+1))

#define _pomofocus_ble_GoalType_MIN pomofocus_ble_GoalType_GOAL_TYPE_LONG_TERM
#define _pomofocus_ble_GoalType_MAX pomofocus_ble_GoalType_GOAL_TYPE_PROCESS
#define _pomofocus_ble_GoalType_ARRAYSIZE ((pomofocus_ble_GoalType)(pomofocus_ble_GoalType_GOAL_TYPE_PROCESS+1))

#define _pomofocus_ble_SessionType_MIN pomofocus_ble_SessionType_SESSION_TYPE_FOCUS
#define _pomofocus_ble_SessionType_MAX pomofocus_ble_SessionType_SESSION_TYPE_LONG_BREAK
#define _pomofocus_ble_SessionType_ARRAYSIZE ((pomofocus_ble_SessionType)(pomofocus_ble_SessionType_SESSION_TYPE_LONG_BREAK+1))

#define _pomofocus_ble_SessionOutcome_MIN pomofocus_ble_SessionOutcome_SESSION_OUTCOME_COMPLETED
#define _pomofocus_ble_SessionOutcome_MAX pomofocus_ble_SessionOutcome_SESSION_OUTCOME_ABANDONED
#define _pomofocus_ble_SessionOutcome_ARRAYSIZE ((pomofocus_ble_SessionOutcome)(pomofocus_ble_SessionOutcome_SESSION_OUTCOME_ABANDONED+1))

#define _pomofocus_ble_SyncState_MIN pomofocus_ble_SyncState_SYNC_STATE_IDLE
#define _pomofocus_ble_SyncState_MAX pomofocus_ble_SyncState_SYNC_STATE_ERROR
#define _pomofocus_ble_SyncState_ARRAYSIZE ((pomofocus_ble_SyncState)(pomofocus_ble_SyncState_SYNC_STATE_ERROR+1))

#define _pomofocus_ble_SyncCommand_MIN pomofocus_ble_SyncCommand_SYNC_COMMAND_START
#define _pomofocus_ble_SyncCommand_MAX pomofocus_ble_SyncCommand_SYNC_COMMAND_CURSOR_UPDATE
#define _pomofocus_ble_SyncCommand_ARRAYSIZE ((pomofocus_ble_SyncCommand)(pomofocus_ble_SyncCommand_SYNC_COMMAND_CURSOR_UPDATE+1))

#define pomofocus_ble_TimerState_phase_ENUMTYPE pomofocus_ble_TimerPhase

#define pomofocus_ble_TimerCommand_action_ENUMTYPE pomofocus_ble_TimerAction

#define pomofocus_ble_Goal_type_ENUMTYPE pomofocus_ble_GoalType



#define pomofocus_ble_SessionRecord_type_ENUMTYPE pomofocus_ble_SessionType
#define pomofocus_ble_SessionRecord_outcome_ENUMTYPE pomofocus_ble_SessionOutcome

#define pomofocus_ble_SyncStatus_state_ENUMTYPE pomofocus_ble_SyncState

#define pomofocus_ble_SyncControl_command_ENUMTYPE pomofocus_ble_SyncCommand


/* Initializer values for message structs */
#define pomofocus_ble_TimerState_init_default    {_pomofocus_ble_TimerPhase_MIN, 0, 0, {0, {0}}, 0}
#define pomofocus_ble_TimerCommand_init_default  {_pomofocus_ble_TimerAction_MIN, {0, {0}}, 0}
#define pomofocus_ble_Goal_init_default          {{0, {0}}, "", _pomofocus_ble_GoalType_MIN, 0, 0}
#define pomofocus_ble_GoalList_init_default      {0, {pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default, pomofocus_ble_Goal_init_default}}
#define pomofocus_ble_SelectedGoal_init_default  {{0, {0}}}
#define pomofocus_ble_SessionRecord_init_default {{0, {0}}, {0, {0}}, 0, 0, 0, 0, _pomofocus_ble_SessionType_MIN, _pomofocus_ble_SessionOutcome_MIN, 0, "", "", ""}
#define pomofocus_ble_SyncStatus_init_default    {0, 0, {0, {0}}, _pomofocus_ble_SyncState_MIN}
#define pomofocus_ble_SyncControl_init_default   {_pomofocus_ble_SyncCommand_MIN, 0, {0, {0}}}
#define pomofocus_ble_TimerState_init_zero       {_pomofocus_ble_TimerPhase_MIN, 0, 0, {0, {0}}, 0}
#define pomofocus_ble_TimerCommand_init_zero     {_pomofocus_ble_TimerAction_MIN, {0, {0}}, 0}
#define pomofocus_ble_Goal_init_zero             {{0, {0}}, "", _pomofocus_ble_GoalType_MIN, 0, 0}
#define pomofocus_ble_GoalList_init_zero         {0, {pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero, pomofocus_ble_Goal_init_zero}}
#define pomofocus_ble_SelectedGoal_init_zero     {{0, {0}}}
#define pomofocus_ble_SessionRecord_init_zero    {{0, {0}}, {0, {0}}, 0, 0, 0, 0, _pomofocus_ble_SessionType_MIN, _pomofocus_ble_SessionOutcome_MIN, 0, "", "", ""}
#define pomofocus_ble_SyncStatus_init_zero       {0, 0, {0, {0}}, _pomofocus_ble_SyncState_MIN}
#define pomofocus_ble_SyncControl_init_zero      {_pomofocus_ble_SyncCommand_MIN, 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define pomofocus_ble_TimerState_phase_tag       1
#define pomofocus_ble_TimerState_remaining_seconds_tag 2
#define pomofocus_ble_TimerState_elapsed_seconds_tag 3
#define pomofocus_ble_TimerState_goal_id_tag     4
#define pomofocus_ble_TimerState_session_count_tag 5
#define pomofocus_ble_TimerCommand_action_tag    1
#define pomofocus_ble_TimerCommand_goal_id_tag   2
#define pomofocus_ble_TimerCommand_focus_duration_tag 3
#define pomofocus_ble_Goal_id_tag                1
#define pomofocus_ble_Goal_title_tag             2
#define pomofocus_ble_Goal_type_tag              3
#define pomofocus_ble_Goal_target_sessions_tag   4
#define pomofocus_ble_Goal_completed_today_tag   5
#define pomofocus_ble_GoalList_goals_tag         1
#define pomofocus_ble_SelectedGoal_goal_id_tag   1
#define pomofocus_ble_SessionRecord_id_tag       1
#define pomofocus_ble_SessionRecord_goal_id_tag  2
#define pomofocus_ble_SessionRecord_started_at_tag 3
#define pomofocus_ble_SessionRecord_ended_at_tag 4
#define pomofocus_ble_SessionRecord_planned_duration_tag 5
#define pomofocus_ble_SessionRecord_actual_duration_tag 6
#define pomofocus_ble_SessionRecord_type_tag     7
#define pomofocus_ble_SessionRecord_outcome_tag  8
#define pomofocus_ble_SessionRecord_focus_quality_tag 9
#define pomofocus_ble_SessionRecord_intention_tag 10
#define pomofocus_ble_SessionRecord_reflection_tag 11
#define pomofocus_ble_SessionRecord_distraction_note_tag 12
#define pomofocus_ble_SyncStatus_pending_sessions_tag 1
#define pomofocus_ble_SyncStatus_total_stored_tag 2
#define pomofocus_ble_SyncStatus_last_synced_id_tag 3
#define pomofocus_ble_SyncStatus_state_tag       4
#define pomofocus_ble_SyncControl_command_tag    1
#define pomofocus_ble_SyncControl_ack_count_tag  2
#define pomofocus_ble_SyncControl_last_synced_id_tag 3

/* Struct field encoding specification for nanopb */
#define pomofocus_ble_TimerState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    phase,             1) \
X(a, STATIC,   SINGULAR, UINT32,   remaining_seconds,   2) \
X(a, STATIC,   SINGULAR, UINT32,   elapsed_seconds,   3) \
X(a, STATIC,   SINGULAR, BYTES,    goal_id,           4) \
X(a, STATIC,   SINGULAR, UINT32,   session_count,     5)
#define pomofocus_ble_TimerState_CALLBACK NULL
#define pomofocus_ble_TimerState_DEFAULT NULL

#define pomofocus_ble_TimerCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   SINGULAR, BYTES,    goal_id,           2) \
X(a, STATIC,   SINGULAR, UINT32,   focus_duration,    3)
#define pomofocus_ble_TimerCommand_CALLBACK NULL
#define pomofocus_ble_TimerCommand_DEFAULT NULL

#define pomofocus_ble_Goal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    id,                1) \
X(a, STATIC,   SINGULAR, STRING,   title,             2) \
X(a, STATIC,   SINGULAR, UENUM,    type,              3) \
X(a, STATIC,   SINGULAR, UINT32,   target_sessions,   4) \
X(a, STATIC,   SINGULAR, UINT32,   completed_today,   5)
#define pomofocus_ble_Goal_CALLBACK NULL
#define pomofocus_ble_Goal_DEFAULT NULL

#define pomofocus_ble_GoalList_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  goals,             1)
#define pomofocus_ble_GoalList_CALLBACK NULL
#define pomofocus_ble_GoalList_DEFAULT NULL
#define pomofocus_ble_GoalList_goals_MSGTYPE pomofocus_ble_Goal

#define pomofocus_ble_SelectedGoal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    goal_id,           1)
#define pomofocus_ble_SelectedGoal_CALLBACK NULL
#define pomofocus_ble_SelectedGoal_DEFAULT NULL

#define pomofocus_ble_SessionRecord_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    id,                1) \
X(a, STATIC,   SINGULAR, BYTES,    goal_id,           2) \
X(a, STATIC,   SINGULAR, INT64,    started_at,        3) \
X(a, STATIC,   SINGULAR, INT64,    ended_at,          4) \
X(a, STATIC,   SINGULAR, UINT32,   planned_duration,   5) \
X(a, STATIC,   SINGULAR, UINT32,   actual_duration,   6) \
X(a, STATIC,   SINGULAR, UENUM,    type,              7) \
X(a, STATIC,   SINGULAR, UENUM,    outcome,           8) \
X(a, STATIC,   SINGULAR, UINT32,   focus_quality,     9) \
X(a, STATIC,   SINGULAR, STRING,   intention,        10) \
X(a, STATIC,   SINGULAR, STRING,   reflection,       11) \
X(a, STATIC,   SINGULAR, STRING,   distraction_note,  12)
#define pomofocus_ble_SessionRecord_CALLBACK NULL
#define pomofocus_ble_SessionRecord_DEFAULT NULL

#define pomofocus_ble_SyncStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pending_sessions,   1) \
X(a, STATIC,   SINGULAR, UINT32,   total_stored,      2) \
X(a, STATIC,   SINGULAR, BYTES,    last_synced_id,    3) \
X(a, STATIC,   SINGULAR, UENUM,    state,             4)
#define pomofocus_ble_SyncStatus_CALLBACK NULL
#define pomofocus_ble_SyncStatus_DEFAULT NULL

#define pomofocus_ble_SyncControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, STATIC,   SINGULAR, UINT32,   ack_count,         2) \
X(a, STATIC,   SINGULAR, BYTES,    last_synced_id,    3)
#define pomofocus_ble_SyncControl_CALLBACK NULL
#define pomofocus_ble_SyncControl_DEFAULT NULL

extern const pb_msgdesc_t pomofocus_ble_TimerState_msg;
extern const pb_msgdesc_t pomofocus_ble_TimerCommand_msg;
extern const pb_msgdesc_t pomofocus_ble_Goal_msg;
extern const pb_msgdesc_t pomofocus_ble_GoalList_msg;
extern const pb_msgdesc_t pomofocus_ble_SelectedGoal_msg;
extern const pb_msgdesc_t pomofocus_ble_SessionRecord_msg;
extern const pb_msgdesc_t pomofocus_ble_SyncStatus_msg;
extern const pb_msgdesc_t pomofocus_ble_SyncControl_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pomofocus_ble_TimerState_fields &pomofocus_ble_TimerState_msg
#define pomofocus_ble_TimerCommand_fields &pomofocus_ble_TimerCommand_msg
#define pomofocus_ble_Goal_fields &pomofocus_ble_Goal_msg
#define pomofocus_ble_GoalList_fields &pomofocus_ble_GoalList_msg
#define pomofocus_ble_SelectedGoal_fields &pomofocus_ble_SelectedGoal_msg
#define pomofocus_ble_SessionRecord_fields &pomofocus_ble_SessionRecord_msg
#define pomofocus_ble_SyncStatus_fields &pomofocus_ble_SyncStatus_msg
#define pomofocus_ble_SyncControl_fields &pomofocus_ble_SyncControl_msg

/* Maximum encoded size of messages (where known) */
#define POMOFOCUS_BLE_POMOFOCUS_PB_H_MAX_SIZE    pomofocus_ble_GoalList_size
#define pomofocus_ble_GoalList_size              1370
#define pomofocus_ble_Goal_size                  134
#define pomofocus_ble_SelectedGoal_size          18
#define pomofocus_ble_SessionRecord_size         989
#define pomofocus_ble_SyncControl_size           26
#define pomofocus_ble_SyncStatus_size            32
#define pomofocus_ble_TimerCommand_size          26
#define pomofocus_ble_TimerState_size            38

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
