/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "pomofocus.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pomofocus_ble_TimerState, pomofocus_ble_TimerState, AUTO)


PB_BIND(pomofocus_ble_TimerCommand, pomofocus_ble_TimerCommand, AUTO)


PB_BIND(pomofocus_ble_Goal, pomofocus_ble_Goal, AUTO)


PB_BIND(pomofocus_ble_GoalList, pomofocus_ble_GoalList, 2)


PB_BIND(pomofocus_ble_SelectedGoal, pomofocus_ble_SelectedGoal, AUTO)


PB_BIND(pomofocus_ble_SessionRecord, pomofocus_ble_SessionRecord, 2)


PB_BIND(pomofocus_ble_SyncStatus, pomofocus_ble_SyncStatus, AUTO)


PB_BIND(pomofocus_ble_SyncControl, pomofocus_ble_SyncControl, AUTO)

















