/**
 * Generates TypeScript types from the OpenAPI spec using openapi-typescript.
 *
 * Usage: npx tsx packages/data-access/scripts/generate-client.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, '..');
const workspaceRoot = resolve(packageRoot, '../..');

const SPEC_PATH = resolve(workspaceRoot, 'apps/api/openapi.json');
const OUTPUT_PATH = resolve(packageRoot, 'src/generated/api-types.ts');

const DO_NOT_EDIT_HEADER = [
  '/* eslint-disable */',
  '/* This file is auto-generated by openapi-typescript. DO NOT EDIT. */',
  '',
].join('\n');

async function main(): Promise<void> {
  const specUrl = pathToFileURL(SPEC_PATH);

  const ast = await openapiTS(specUrl, {
    exportType: true,
  });

  const output = DO_NOT_EDIT_HEADER + astToString(ast);

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, output, 'utf-8');

  // eslint-disable-next-line no-console
  console.log(`Generated API types → ${OUTPUT_PATH}`);
}

void main();
